---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      priorityClassName: infra
      containers:
      - name: elasticsearch
        image: elasticsearch:6.6.0
        env:
          - name: CLUSTER_NAME
            value: logs
          - name: HTTP_ENABLE
            value: "true"
          - name: MINIMUM_NUMBER_OF_MASTERS
            value: "2"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NETWORK_ADDRESS_CACHE_NEGATIVE_TTL
            value: "2"
          - name: NETWORK_ADDRESS_CACHE_TTL
            value: "2"
          - name: NETWORK_HOST
            value: "0.0.0.0"
          # PROCESSORS NEED TO BE AN INTEGER - SET LIMITS CPU ACCORDINGLY
          - name: PROCESSORS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 2
        ports:
        - containerPort: 9200
          name: http
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 40
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
