apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: mysql
  name: dev-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: dev-mysql-pass
        image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      initContainers:
      - command:
        - sh
        - -c
        - echo dev-wordpress && echo dev-mysql
        image: busybox
        name: init1
      - command:
        - sh
        - -c
        - echo 10.0.2.3
        image: busybox
        name: init2
      volumes:
      - emptyDir: {}
        name: mysql-persistent-storage
