apiVersion: my.group.org/v1alpha1
kind: SoftwareVersions
metadata:
  name: dev-software-versions
spec:
  charts:
    mysql:
      location: https://github.com/helm/charts/blob/
      reference: latest
      subpath: mysql
      type: git
    wordpress:
      location: https://github.com/helm/charts/blob/
      reference: latest
      subpath: wordpress
      type: git
  images:
    mysql:
      registory: docker.io
      repository: mysql
      tag: "5.7"
    wordpress:
      registory: docker.io
      repository: wordpress
      tag: 5.2.1-apache
