apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: external.dns
    service.beta.kubernetes.io/aws-load-balancer-extra-security-group: aws.load.balancer.extra.security.group
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: aws.load.balancer.ssl.cert
  name: ingress-validation-webhook
  namespace: ingress-nginx
spec:
  ports:
  - name: admission
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: ingress-nginx
