apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: environment
    files:
      - name
      - domain
      - branch
# vars:
#   - name: ENV
#     objref:
#       apiVersion: v1
#       kind: ConfigMap
#       name: environment
#     fieldref:
#       fieldpath: data.name
#   - name: DOMAIN
#     objref:
#       apiVersion: v1
#       kind: ConfigMap
#       name: environment
#     fieldref:
#       fieldpath: data.domain
#   - name: BRANCH
#     objref:
#       apiVersion: v1
#       kind: ConfigMap
#       name: environment
#     fieldref:
#       fieldpath: data.branch
generatorOptions:
 disableNameSuffixHash: true
