apiVersion: kustomize.config.k8s.io/v1
kind: Values
metadata:
  name: shared
spec:
  env:
  - name: WORDPRESS_DB_USER
    valueFrom:
      secretKeyRef:
        key: user
        name: wordpress-db-auth
  - name: WORDPRESS_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: wordpress-db-auth
