apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: postgres
  name: overlay-base1-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
