apiVersion: v1
kind: PersistentVolume
metadata:
  name: dumpster-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  flexVolume:
    driver: azure/blobfuse
    options:
      container: $(CONTAINER_NAME)
      mountoptions: --file-cache-timeout-in-seconds=120
      tmppath: /tmp/blobfuse
    secretRef:
      name: dumpster-blobfuse-credentials
