apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Proper behavior is only obtained if
# nameSuffix is not set in here
# but in the overlay
nameSuffix: -suffix

configMapGenerator:
- name: bar
  files: [file2]
