commonLabels:
  app.kubernetes.io/name: gateway
  app.kubernetes.io/instance: gateway-abcxzy
  app.kubernetes.io/component: microservice
  app.kubernetes.io/part-of: micro-starter-kit
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

namePrefix: gateway

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=gatewaysrv
      # - MICRO_SERVER_ADVERTISE="$(GATEWAY_SRV_ENDPOINT):8080"
      - MICRO_API_NAMESPACE=""
      - MICRO_API_HANDLER=rpc
      - MICRO_API_ENABLE_RPC="true"
      - MICRO_LOG_LEVEL=debug
      - CORS_ALLOWED_HEADERS="Authorization,Content-Type"
      - CORS_ALLOWED_ORIGINS="*"
      - CORS_ALLOWED_METHODS="POST,GET"

vars:
  - name: GATEWAY_SRV_ENDPOINT
    objref:
      kind: Service
      name: srv
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
