apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-sidecar
spec:
  template:
    spec:
      containers:
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=$(ACCOUNT_SERVICE_NAME)",
            "--server_address=0.0.0.0:8080"
            ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
