apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/cert-manager.yaml

patchesStrategicMerge:
- overlays/production/cert-manager.yaml

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1beta1
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  path: "./jsonpatch.yaml"
