apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  env: $(Values.nodeenv.spec.env)

secretGenerator:
- name: core
  type: Opaque
  envs:
  - secrets.txt
  behavior: replace

patchesStrategicMerge:
- values.nodeenv.yaml
- values.sentryenv.yaml
