environment: production
name: emailersrv
version: v0.1.0
log:
  level: info
  format: json
observability:
  metrics:
    address: prometheus:8125
    flushInterval: 1000000000
  tracing:
    address: jaeger:6831
    flushInterval: 5000000000
email:
  username: yourGmailUsername
  password: yourGmailAppPassword
  emailServer: smtp.gmail.com
  port: 587
  from: xmlking@gmail.com
