namePrefix: staging-
commonLabels:
  env: staging
  team: override-foo
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../package/
configMapGenerator:
  - name: configmap-in-overlay
    literals:
      - hello=world
  - name: configmap-in-base
    behavior: replace
    literals:
      - foo=override-bar
secretGenerator:
- name: secret-in-base
  behavior: merge
  literals:
  - proxy=haproxy
