apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: sentry

resources:
- ./deployment.yaml
- ./values.nodeenv.yaml
- ./values.sentryenv.yaml

secretGenerator:
- name: core
  type: Opaque
  envs:
  - secrets.txt
