apiVersion: kustomize.config.k8s.io/v1
kind: Values
metadata:
  name: sentryenv
spec:
  env: dev
  readinessProbe:
    exec:
      command:
      - /opt/sentryenv/bin/zkOK.sh
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 5
