namespace: prod-ns
namePrefix: prod-

commonLabels:
  environment: production
commonAnnotations:
  note: Hello, I am production!

bases:
  - ../../bases

# resources:
#   - resources/namespace.yaml
#   - resources/hpa.yaml

patchesStrategicMerge:
  - patches/replica_count.yaml
  - patches/resource_limit.yaml

patches:
  - path: patches/health-sidecar.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=service

configMapGenerator:
  - behavior: merge
    files:
      - config/config.yaml
    name: configs

secretGenerator:
  - behavior: replace
    literals:
      - postgres-password=postgres123
    name: postgres-secrets

images:
  - name: postgres
    newTag: 11.5-alpine
  - name: docker.io/bitnami/postgresql
    newTag: "10.7.0"
  - name: progrium/consul
    newTag: consul-0.4
  - name: xmlking/account-srv
    newTag: v1.0.1
