apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: SOME_ENV
          value: another value
        image: nginx
        name: nginx
