resources:
- nodejsapp-service.yaml

configMapGenerator:
- name: nodejs-test-cm
  literals:
    - branch=develop
    - build=20191025
    - external_ip=10.0.0.3
    - external_port=3000

# This kustomization.yaml leverages auto-var feature
# instead of doing it manually
# Uncommment if you do not have access to the feature.
# configurations:
# - kustomizeconfig/var_references.yaml

# vars:
# - name: ConfigMap.nodejs-test-cm.data.external_ip
#   objref:
#     kind: ConfigMap
#     name: nodejs-test-cm
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.external_ip
# - name: ConfigMap.nodejs-test-cm.data.external_port
#   objref:
#     kind: ConfigMap
#     name: nodejs-test-cm
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.external_port
