apiVersion: v1
kind: Service
metadata:
  name: "nodejs-test"
  labels:
    service: "nodejs-test"
spec:
  ports:
  - name: client-connect
    port: "$(ConfigMap.nodejs-test-cm.data.external_port)"
    targetPort: 3000
  selector:
    app: "nodejs-test"
  type: ClusterIP
  externalIPs:
  - "$(ConfigMap.nodejs-test-cm.data.external_ip)"
