apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Proper behavior is only obtained if
# nameSuffix is not set in the base
# layer but set here in the overlay
# nameSuffix: -suffix

resources:
- ../base
- podspec.yaml
