apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: component1
  name: component1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component1
  template:
    metadata:
      labels:
        app: component1
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - cat /etc/config/component1 && sleep 60
        env:
        - name: APP_USER
          value: myuser
        image: k8s.gcr.io/busybox
        name: component1
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: settings
            path: component1
          name: global
        name: config-volume
