---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-srv
  labels:
    app: account-srv
spec:
  template:
    spec:
      containers:
        - name: account-srv
          resources:
            requests:
              cpu: 250m
              memory: 1G
            limits:
              cpu: 500m
              memory: 2G
