apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: my-label
  name: my-role
  namespace: my-namespace
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
