apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: my-label
  name: my-rolebinding
  namespace: my-other-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: my-other-namespace
- kind: ServiceAccount
  name: my-other-namespace-sa
  namespace: my-other-namespace
- kind: ServiceAccount
  name: my-namespace-sa
  namespace: my-namespace
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-1
