apiVersion: v1
data:
  password: dGhlcGFzc3dvcmQ=
  sentryDNS: MTI3LjAuMC4x
  username: dGhldXNlcg==
kind: Secret
metadata:
  name: core-966hh9bc88
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentry
  name: core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentry
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sentry
    spec:
      containers:
      - env:
        - name: SENTRY_DNS
          valueFrom:
            secretKeyRef:
              key: sentryDNS
              name: core-966hh9bc88
        image: sentryimage:1.0
        imagePullPolicy: Always
        name: sentry
