apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NS)

commonLabels:
  environment: integration
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am integration!

bases:
  - ../../bases/micros

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=integration
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - MICRO_LOG_LEVEL=debug
      # profile specific variables
      - MICRO_REGISTER_TTL="60"
      - MICRO_REGISTER_INTERVAL="30"
      # - MICRO_SELECTOR=static # static/memory still not working with gateway & proxy
      # - MICRO_REGISTRY=memory
      # following endpoint overwrites (in config.yaml) should be enabled only when  MICRO_SELECTOR=static is used.
      # - ACCOUNTSRV_ENDPOINT=$(ACCOUNT_SRV_ENDPOINT)
      # - GREETERSRV_ENDPOINT=$(GREETER_SRV_ENDPOINT)
      # - EMAILERSRV_ENDPOINT=$(EMAILER_SRV_ENDPOINT)
      # - GATEWAYSRV_ENDPOINT=$(GATEWAY_SRV_ENDPOINT)
      # - PROXYSRV_ENDPOINT=$(PROXY_SRV_ENDPOINT)

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=e2e-real-pass

replicas:
  - name: srv
    count: 1

images:
  - name: etcd
    newTag: 3.3.15
  - name: postgres
    newTag: 11.5-alpine
  - name: micro/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: v1.15.1
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)
