apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ./mycrd.yaml
- ./ingress.yaml
- ./service.yaml
- ./deployment.yaml

transformers:
- ./kustomizeconfig/namespacetransformer.yaml
- ./kustomizeconfig/commonlabelstransformer.yaml
