apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dply2
  namespace: default
spec:
  template:
    metadata:
      labels:
        from: overlay
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: dply1
  name: dply1
spec:
  selector:
    matchLabels:
      app: dply1
  template:
    metadata:
      labels:
        app: dply1
    spec:
      containers:
      - image: alpine
        name: dply1
