apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io\/instance: var-value-in-config-map
  name: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io\/instance: var-value-in-config-map
  template:
    metadata:
      labels:
        app.kubernetes.io\/instance: var-value-in-config-map
    spec:
      containers:
      - image: myapp
        name: main
