---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
spec:
  template:
    spec:
      containers:
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.11.0
        command:
        - /bin/mysqld_exporter
        args:
        - --web.listen-address=:9104
        - --log.level=info
        - --log.format=logger:stderr?json=true
        livenessProbe:
          httpGet:
            path: /
            port: 9104
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 9104
        env:
        - name: DATA_SOURCE_NAME
          value: $(DB_USER):$(DB_PASSWORD)@(127.0.0.1:3306)/
        ports:
        - name: metrics
          containerPort: 9104
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 65534
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy
        imagePullPolicy: IfNotPresent
        command:
        - /cloud_sql_proxy
        args:
        - -instances=$(MASTER_INSTANCE)=tcp:127.0.0.1:3306
        - -credential_file=/secrets/cloudsql/google_credentials
        - -dir=/cloudsql
        ports:
        - name: mysql
          containerPort: 3306
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 65534
        volumeMounts:
        - name: cloudsql-settings
          mountPath: /secrets/cloudsql
          readOnly: true
