apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- behavior: merge
  files:
  - application-prod.properties
  name: demo-configmap
patchesStrategicMerge:
- patch.yaml
- memorylimit_patch.yaml
- healthcheck_patch.yaml
namePrefix: prod-
commonLabels:
  env: prod
