apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels: $(EndpointCatalogue.endpoints.spec.wordpress.labels)
spec:
  ports:
    - port: 80
  selector: $(EndpointCatalogue.endpoints.spec.wordpress.labels)
  type: LoadBalancer
