---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namePrefix: scenario1-dev-normal-v1-
resources:
- ../../common             # Has Deployment
- ../../scenario/scenario1 # apply changes necessary for scenario1
- ../../environment/dev    # apply changes for dev
- ../../processor/normal   # apply changes for normal
- ../../version/v1         # Apply v1
