apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus
    cluster: ca-1-dev
    heritage: Tiller
    release: istio
  name: prometheus
  namespace: istio-system
