apiVersion: v1
kind: Service
metadata:
  name: redissession
spec:
  selector:
    app: redissession
  ports:
  - name: web
    port: $(Values.redissession.spec.port)
    targetPort: $(Values.redissession.spec.targetPort)
