kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-b
spec:
  replicas: 1
  template:
    metadata:
      name: service-b
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: hack4easy/kubesim_health-bmd64:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8081
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
        ports:
        - name: service-b
          containerPort: 8081
