apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
spec:
  selector:
    namespaceSelector:
      matchNames:
      - IWANTTOREPLACETHIS
  endpoints:
  - port: metrics
    honorlablels: true
    interval: 10s
    scrapeTimeout: 10s
    etc: etc
