apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: foocorp-operators-registry
spec:
  image: docker-registry.default.svc:/foocorp/foocorp-operators-registry@sha256:NOTIMPORTANTFORTHETEST
