apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

transformers:
- ./kustomizeconfig/imagetransformer.yaml
- ./kustomizeconfig/namesuffixtransformer.yaml
- ./kustomizeconfig/commonlabelstransformer.yaml
- ./kustomizeconfig/patchstrategicmergetransformer.yaml
