apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# patchesStrategicMerge:
# - ./gateway.yaml

patchesJson6902:
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: Gateway
    name: my-gateway
  path: patch.yaml
