apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        foo: bar
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      initContainers:
      - command:
        - sh
        - -c
        - echo wordpress && echo mysql
        image: busybox
        name: init1
      - command:
        - sh
        - -c
        - echo 10.0.2.3
        image: busybox
        name: init2
      volumes:
      - emptyDir: {}
        name: wordpress-persistent-storage
