apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/part-of: elasticsearch
  name: elasticsearch-data-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/part-of: elasticsearch
  serviceName: elasticsearch-data-v1
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: elasticsearch
        tier: logging-plane
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
            weight: 100
  updateStrategy:
    type: RollingUpdate
