---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../intermediate-base

namePrefix: production-
namespace: sandbox

configMapGenerator:
- envs:
  - env.properties
  name: env
  namespace: sandbox
  behavior: merge
