apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - test-kus/overlays
images:
  - name: leaf/esp-service
    newName: 11111.dkr.ecr.us-west-2.amazonaws.com/leaf/esp-service
    newTag: latest
