apiVersion: v1
kind: Service
metadata:
  name: persistencelayer
spec:
  selector:
    app: persistencelayer
  ports:
  - name: web
    port: $(Values.persistencelayer.spec.port)
    targetPort: $(Values.persistencelayer.spec.targetPort)
