---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

patchesStrategicMerge:
- passphrases.yaml
- versions.yaml
- endpoints.yaml
- common-addresses.yaml

resources:
- ../base
- devtools.yaml

vars:
- name: SoftwareVersions.software-versions.spec.charts.wordpress
  objref:
    apiVersion: my.group.org/v1alpha1
    kind: SoftwareVersions
    name: software-versions
  fieldref:
    fieldpath: spec.charts.wordpress
- name: SoftwareVersions.software-versions.spec.charts.mysql
  objref:
    apiVersion: my.group.org/v1alpha1
    kind: SoftwareVersions
    name: software-versions
  fieldref:
    fieldpath: spec.charts.mysql
- name: SoftwareVersions.software-versions.spec.images.wordpress
  objref:
    apiVersion: my.group.org/v1alpha1
    kind: SoftwareVersions
    name: software-versions
  fieldref:
    fieldpath: spec.images.wordpress
- name: SoftwareVersions.software-versions.spec.images.mysql
  objref:
    apiVersion: my.group.org/v1alpha1
    kind: SoftwareVersions
    name: software-versions
  fieldref:
    fieldpath: spec.images.mysql
