kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-a
spec:
  replicas: 1
  template:
    metadata:
      name: service-a
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: hack4easy/kubesim_health-amd64:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8081
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
        ports:
        - name: service-a
          containerPort: 8081
