commonLabels:
  app.kubernetes.io/name: emailer-srv
  app.kubernetes.io/instance: emailer-srv-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: emailer-

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: config
    files:
      - config/config.yaml
  # - name: env-vars
  - name: env-vars1
    literals:
      - SERVICE_NAME=$(EMAILER_SERVICE_NAME)
      - DATABASE_HOST=$(DATABASE_SERVICE_NAME)

vars:
  - name: EMAILER_SERVICE_NAME
    objref:
      kind: Service
      name: srv
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
