apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foo
spec:
  rules:
    - host: foo$(ConfigMap.environment.data.branch).$(ConfigMap.environment.data.name).$(ConfigMap.environment.data.domain)
      http:
        paths:
        - backend:
            serviceName: foo
            servicePort: http
