apiVersion: v1
data:
  application.properties: |
    app.name=Staging Kinflate Demo
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://<staging_db_ip>:3306/db_example
    spring.datasource.username=root
    spring.datasource.password=admin
  foo: bar
  staging: ""
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: staging-demo-configmap-6m4cgm6h26
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbdemo
  name: staging-sbdemo
spec:
  ports:
  - port: 8080
  selector:
    app: sbdemo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sbdemo
  name: staging-sbdemo
spec:
  selector:
    matchLabels:
      app: sbdemo
  template:
    metadata:
      labels:
        app: sbdemo
    spec:
      containers:
      - image: jingfang/sbdemo
        name: sbdemo
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /config
          name: demo-config
      volumes:
      - configMap:
          name: staging-demo-configmap-6m4cgm6h26
        name: demo-config
