---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./catalogues/versions.yaml
- ./catalogues/endpoints.yaml
- ./catalogues/common-addresses.yaml
- ./wordpress/deployment.yaml
- ./wordpress/service.yaml
- ./mysql/deployment.yaml
- ./mysql/secret.yaml
- ./mysql/service.yaml

configurations:
- kustomizeconfig/Chart.yaml
- kustomizeconfig/CommonAddresses.yaml
- kustomizeconfig/EndpointCatalogue.yaml
- kustomizeconfig/SoftwareVersions.yaml
- kustomizeconfig/Deployment.yaml
- kustomizeconfig/Service.yaml

vars:

inlines:
