apiVersion: v1
data:
  kustomization.yaml: |
    resources:
      - base

    configMapGenerator:
      - name: config
        namespace: test
        files:
          - kustomization.yaml

    patchesStrategicMerge:
      - patch.yaml
kind: ConfigMap
metadata:
  name: config-8c5k2mgt28
  namespace: test
