apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# There is a real bug here in kustomize
# rolebinding will not be updated properly
# namePrefix: pfx1-

namespace: my-namespace

resources:
- ./service-account.yaml
- ./rolebinding.yaml
- ./role.yaml
