---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- rollout.yaml
- deployment.yaml
- values.yaml

configurations:
- kustomizeconfig.yaml

vars:
  - name: DEPLOYMENT_COLOR
    objref:
      apiVersion: kustomize.config.k8s.io/v1
      kind: Values
      name: file1
    fieldref:
      fieldpath: spec.deploymentColor
