apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: customPrefixer
suffix: -canary
fieldSpecs:
- kind: Deployment
  path: metadata/name
- kind: Service
  path: metadata/name
- kind: Ingress
  path: spec/backend/serviceName

