apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: api
  name: app-example
spec:
  descriptor:
    type: simple
    version: v1.2.3
  selector:
    matchLabels:
      app: api
