apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: MyDeployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: $(Values.file1.spec.strategy)
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        ports:
        - containerPort: $(Values.file1.spec.port)
          name: mysql
