apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfx-app
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
        - mountPath: /data
          name: appMnt
      volumes:
      - azureFile:
          readOnly: true
          secretName: pfx-storage-secret
          shareName: appMnt-share
        name: appMnt
