apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: SOME_ENV
          value: $(KUSTOMIZE_MYCONFIGMAP_VARIABLE)
