---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: monitoring
nameSuffix: -log
commonLabels:
  app.kubernetes.io/instance: log
  instance: log

resources:
  - elasticstack
