apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: gateway
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          args:
            - "api"
            - "--handler=rpc"
            - "--address=0.0.0.0:8080"
          env:
            - name: MICRO_SERVER_NAME
              value: gateway
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8989
          ports:
            - name: gateway-http
              containerPort: 8080
              protocol: TCP
