apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ./etherpad-lite/lib/etherpad-lite-k8s-kubedb-mysql
commonLabels:
  k8s.permanent.cloud/appInstallation.id: add961a2-b5c7-4ccd-b3c7-66f7c03c9c6e
kind: Kustomization
namePrefix: ai-zv58kz2nbox64fkrqptr94nurvqoxz88o52
