apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeapp-ns

commonLabels:
  app: kubeapp

resources:
- ./namespace.yaml
- ./mycrd.yaml
- ./ingress.yaml
- ./service.yaml
- ./deployment.yaml
