namePrefix: staging-
commonLabels:
  env: staging
patchesStrategicMerge:
  - patches/deployment-patch1.yaml
  - patches/deployment-patch2.yaml
resources:
  - ../package/
configMapGenerator:
  - name: configmap-in-overlay
    literals:
      - hello=world
