apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv
spec:
  template:
    spec:
      containers:
        - name: srv
          # This is the import path for the Go binary to build and run.
          # image: github.com/xmlking/micro-starter-kit/srv/account
          image: xmlking/account-srv:latest
          imagePullPolicy: Always
          ports:
            - name: grpc-port
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /config
          envFrom:
            - configMapRef:
                name: env-vars
            - secretRef:
                name: secrets
      volumes:
        - name: config
          configMap:
            name: config
