apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv
spec:
  template:
    # metadata:
    #   annotations:
    #     sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: srv
          image: micro/micro:latest
          imagePullPolicy: Always
          args:
            - "proxy"
          ports:
            - name: grpc-proxy
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-vars
            - configMapRef:
                name: env-vars-common
