---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/instance: review-myapp-mysqld-exporter
  app.mintel.com/pipeline-stage: review
  app.mintel.com/env: dev

namePrefix: review-

resources:
- ../instance-specific

patchesStrategicMerge:
- patches/remove-cloud-sql-proxy.yaml
- patches/add-vars-to-exporter-main.yaml

configMapGenerator:
- envs:
  - properties/cluster.properties
  name: cluster-properties
  namespace: mynamespace
