apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: myapp
  template:
    metadata:
      labels:
        microservice: myapp
    spec:
      containers:
      - name: myapp
        image: alpine:latest

