namespace: dev-ns
namePrefix: dev-

commonLabels:
  environment: development
commonAnnotations:
  note: Hello, I am dev!

bases:
  - ../../bases

# imagePullPolicy: Always

configMapGenerator:
  - behavior: merge
    files:
      - config/config.yaml
    name: configs
