kind: Secret
metadata:
  name: auth-tls-secret
  namespace: ns1
type: kubernetes.io/tls
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  dummy: ""
