namePrefix: staging-
commonLabels:
  env: staging
patchesStrategicMerge:
  - deployment-patch2.yaml
  - deployment-patch1.yaml
resources:
  - ../package/
configMapGenerator:
  - name: configmap-in-overlay
    literals:
      - hello=world
