---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mms-app-efs
  namespace: mms-app
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-999aaa999
