apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
          - name: app
            volumeMounts:
            - name: appMnt
              mountPath: /data
      volumes:
      - name: appMnt
        azureFile:
          secretName: $(STORAGE_SECRET)
          shareName: appMnt-share
          readOnly: true
