namePrefix: pfx-

resources:
- deployment.yaml
- secret.yaml

configurations:
- kustomizeconfig.yaml

vars:
- name : STORAGE_SECRET
  objref:
    kind: Secret
    name: storage-secret
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
