apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: kustomizedns
spec:
  endpoints:
  - etc: etc
    honorlablels: true
    interval: 10s
    port: metrics
    scrapeTimeout: 10s
  selector:
    namespaceSelector:
      matchNames:
      - kustomizedns
