apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: prometheus
  namespace: kustomizedns
spec:
  alerting:
    alertmanagers:
    - name: alertmanager
      namespace: kustomizedns
      port: alertmanager
  replicas: 2
  ruleSelector: {}
  securityContext: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
