apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: redis
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
