apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: dev
  name: my-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - image: my-frontend-image
        name: my-frontend
