---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-mysqld-exporter
  namespace: mynamespace
spec:
  template:
    spec:
      containers:
      - name: mysqld-exporter
        env:
        - name: DATA_SOURCE_NAME
          value: user:password@(host:3306)/
