apiVersion: v1
kind: Service
metadata:
  labels:
    app: cert-manager
  name: cert-manager-webhook
  namespace: new-cert-namespace
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: cert-manager
  type: ClusterIP
