apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  mintel.com/env: dev

resources:
  - elasticstack-log

vars:
- fieldref:
    fieldPath: data.DOMAIN
  name: DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: environment-properties
- fieldref:
    fieldPath: data.CLUSTER_ENV
  name: CLUSTER_ENV
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: environment-properties

configMapGenerator:
- env: properties/environment.properties
  name: environment-properties
  namespace: kustomize
