---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  template:
    spec:
      containers:
      - name: container1
        env:
        - name: SOME_NAME
          value: somevalue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2
spec:
  template:
    spec:
      containers:
      - name: container1
        env:
        - name: SOME_NAME
          value: somevalue
