apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-overlay1
  namespace: overlay1
spec:
  template:
    spec:
      containers:
      - env:
        - name: SOME_ENV
          value: bar
        name: dep
