apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  name_of_the_service
      prefix: /
      service: name_of_the_service.name_of_the_namespace_we_deploy_into
      host: a_configured_host
  name: name_of_the_service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP
