apiVersion: v1
kind: Service
metadata:
  name: varnish
spec:
  selector:
    app: varnish
  ports:
  - name: web
    port: $(Values.varnish.spec.port)
    targetPort: $(Values.varnish.spec.targetPort)
