apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesStrategicMerge:
- ./backend/deployment.yaml
- ./frontend/deployment.yaml

commonLabels:
  env: production
