environment: production
name: account-srv
version: 0.1.0
log:
  level: debug
  format: text
database:
  dialect: postgres
  host: localhost
  port: 5432
  Username: postgres
  Password: postgres321
  database: postgres
  logging: true
observability:
  metrics:
    address: localhost:8125
    flushInterval: 1000000000
  tracing:
    address: localhost:6831
    flushInterval: 5000000000
email:
  username: yourGmailUsername
  password: yourGmailAppPassword
  emailServer: smtp.gmail.com
  port: 587
  from: xmlking@gmail.com
