apiVersion: v1
data:
  DEBUG: "False"
kind: ConfigMap
metadata:
  name: frontend-web-env-28m45kmmm8
  namespace: sandbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-app
  namespace: sandbox
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args: []
        command: []
        envFrom:
        - configMapRef:
            name: frontend-web-env-28m45kmmm8
        image: container-image
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: main
        ports:
        - containerPort: 8000
          name: http
