apiVersion: v1
data:
  DEBUG: "True"
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: production-frontend-web-env-59bmdgdmkh
  namespace: sandbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-frontend-web-app
  namespace: sandbox
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args: []
        command: []
        envFrom:
        - configMapRef:
            name: production-frontend-web-env-59bmdgdmkh
        image: container-image
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: main
        ports:
        - containerPort: 8000
          name: http
