apiVersion: v1
kind: Service
metadata:
  name: name_of_the_service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  $(Service.name_of_the_service.metadata.name)
      prefix: /
      service: $(Service.name_of_the_service.metadata.name).$(Values.file1.spec.Release.Namespace)
      host: $(Values.file1.spec.url)
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
