apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubeapp
    env: canary
  name: kubeapp-canary
  namespace: kubeapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeapp
      env: canary
  template:
    metadata:
      labels:
        app: kubeapp
        env: canary
      name: kubeapp
    spec:
      containers:
      - image: hack4easy/kubesim_health-amd64:0.1.9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8081
        name: kubeapp
        ports:
        - containerPort: 8081
          name: kubeapp
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
