apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: production

nameSuffix: -production

resources:
- ../base

images:
- name: hack4easy/kubesim_health-amd64
  newTag: 0.1.0
