---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/app: elasticsearch
  app: elasticsearch
  role: master

resources:
- resource.yaml

configurations:
- ./kustomizeconfig/labels.yaml
