apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: my-app

imageTags:
- name: my-app
  newName: localhost/my-app
  newTag: latest

resources:
- ./app

patchesStrategicMerge:
- ./create_volume_one.yaml
- ./create_volume_two.yaml
