apiVersion: apps/v1
kind: Pod
metadata:
  name: extra-overlay2-pod
spec:
  containers:
  - image: nginx
    name: nginx
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: extra-overlay2-data
