---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namePrefix: scenario1-prd-normal-v1-
resources:
- ../../common             # Has Deployment
- ../../scenario/scenario1 # apply changes necessary for scenario1
- ../../environment/prd    # apply changes for prd
- ../../processor/normal   # apply changes for normal
- ../../version/v1         # Apply v1
