apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  namespace: patch
spec:
  template:
    spec:
      containers:
      - livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
