apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: puppetserver
spec:
  targetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       puppetserver
  updatePolicy:
    updateMode: Auto
