apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: foo
  name: inlining-example-foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: alpine
        name: foo
