apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: bar
  name: inlining-example-bar
spec:
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: alpine
        name: foo
