apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- Chief.yaml

configurations:
- kustomizeconfig.yaml

vars:
- fieldref:
    fieldPath: data.batchSize
  name: batchSize
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
