apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    spec:
      containers:
      - name: my-deployment
        image: my-image
        livenessProbe: $(Deployment.probe.spec.template.spec.containers[0].livenessProbe)
      dnsPolicy: $(Deployment.dns.spec.template.spec.dnsPolicy)
      restartPolicy: $(Deployment.restart.spec.template.spec.restartPolicy)
