---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: endpointcatalogues.my.group.org
spec:
  additionalPrinterColumns:
  group: my.group.org
  version: v1alpha1
  names:
    kind: EndpointCatalogue
    plural: endpointcatalogues
    shortNames:
    - pendptcat
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          description: resources contains tbd
          additionalProperties:
            type: object
            properties:
              labels:
                additionalProperties:
                  type: string
                type: object
              pod:
                description: pod contains tbd
                properties:
                  affinity:
                    description: affinity contains tbd
                    type: object
                  lifecycle:
                    description: lifecycle contains tbd
                    type: object
                  replicas:
                    additionalProperties:
                      format: int64
                      type: integer
                    description: replicas contains tbd
                    type: object
                  resources:
                    additionalProperties:
                      properties:
                        limits:
                          description: limits contains tbd
                          properties:
                            cpu:
                              description: cpu contains tbd
                              type: string
                            memory:
                              description: memory contains tbd
                              type: string
                          type: object
                        requests:
                          description: requests contains tbd
                          properties:
                            cpu:
                              description: cpu contains tbd
                              type: string
                            memory:
                              description: memory contains tbd
                              type: string
                          type: object
                      type: object
                    description: resources contains tbd
                    type: object
                type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
...
